# Generated by Django 3.1.2 on 2021-01-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
